#!/bin/bash

echo "Vercelプロジェクトのセットアップを開始します..."
echo "=================================="
echo ""
echo "以下の手順に従ってください："
echo ""
echo "1. Vercelアカウントにログイン:"
echo "   npx vercel login"
echo ""
echo "2. プロジェクトをリンク:"
echo "   npx vercel link"
echo ""
echo "3. プロジェクト情報を取得:"
echo "   cat .vercel/project.json"
echo ""
echo "取得した情報をGitHub Secretsに設定してください："
echo "- VERCEL_ORG_ID: orgIdの値"
echo "- VERCEL_PROJECT_ID: projectIdの値"
echo ""
echo "4. Vercelトークンの取得:"
echo "   https://vercel.com/account/tokens"
echo "   で新しいトークンを作成し、VERCEL_TOKENに設定"